// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uu5v5CefeBFWJ3g58RuWZW
// Component: dZ4nzDGoQBJ
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import MenuHeaderDesktop from "../../MenuHeaderDesktop"; // plasmic-import: RhmfQLZ342T/component
import Footer from "../../Footer"; // plasmic-import: 0UCZXj9Zumd/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_coach_website.module.css"; // plasmic-import: uu5v5CefeBFWJ3g58RuWZW/projectcss
import sty from "./PlasmicIndustryLuxuryGoods.module.css"; // plasmic-import: dZ4nzDGoQBJ/css
import industryIconsLuxurygoodspngX8SdV08N2 from "./images/industryIconsLuxurygoodspng.png"; // plasmic-import: X8SdV08N2/picture
import buttonCaretWhitesvg2S5Jbv6HmTb from "./images/buttonCaretWhitesvg2.svg"; // plasmic-import: S5jbv6HmTb/picture
import illustrationBannerLuxuryGoodspngJkzxvrAAa from "./images/illustrationBannerLuxuryGoodspng.png"; // plasmic-import: JkzxvrAAa/picture
import luxury1Png2Lr73RiQs2 from "./images/luxury1Png2.png"; // plasmic-import: LR73RiQS2/picture
import webSalesTrainingpng70SZ9Vex from "./images/webSalesTrainingpng.png"; // plasmic-import: 70s-Z9vex/picture
import webLuxuryProductpngIY87WaGni from "./images/webLuxuryProductpng.png"; // plasmic-import: iY87waGni/picture
import webCustomerRelationspng8IqsZVd7 from "./images/webCustomerRelationspng.png"; // plasmic-import: 8IQS_ZVd7/picture
import webOnboardingTrainingpng7WY11Mx3O from "./images/webOnboardingTrainingpng.png"; // plasmic-import: 7wY11MX3O/picture

export const PlasmicIndustryLuxuryGoods__VariantProps = new Array();

export const PlasmicIndustryLuxuryGoods__ArgProps = new Array();

function PlasmicIndustryLuxuryGoods__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <MenuHeaderDesktop
            data-plasmic-name={"menuHeaderDesktop"}
            data-plasmic-override={overrides.menuHeaderDesktop}
            className={classNames("__wab_instance", sty.menuHeaderDesktop)}
          />

          <div
            data-plasmic-name={"hero"}
            data-plasmic-override={overrides.hero}
            className={classNames(projectcss.all, sty.hero)}
          >
            <div className={classNames(projectcss.all, sty.columns__wr65D)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__rxHu9)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___05Ulu)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__vMdW)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__ethnp)}
                      displayHeight={"35px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"35px"}
                      loading={"lazy"}
                      src={{
                        src: industryIconsLuxurygoodspngX8SdV08N2,
                        fullWidth: 225,
                        fullHeight: 225,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___54FY
                      )}
                    >
                      {"COACH FOR LUXURY GOODS"}
                    </div>
                  </p.Stack>

                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {"Employee training in the\n"}
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#3E7CB1" }}
                      >
                        {"Luxury Goods industry"}
                      </span>
                    </React.Fragment>
                  </h1>
                </p.Stack>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fnoVr
                  )}
                >
                  {
                    "Ensure your employees exceed in selling highly attractive products and help them maintain valuable customer relations."
                  }
                </div>

                <p.Stack
                  as={"button"}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.button,
                    sty.button__wkefu
                  )}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pLb2
                    )}
                  >
                    {"BOOK A DEMO"}
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___2NPug)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"15px"}
                    loading={"lazy"}
                    src={{
                      src: buttonCaretWhitesvg2S5Jbv6HmTb,
                      fullWidth: 108,
                      fullHeight: 150,
                      aspectRatio: 0.722222
                    }}
                  />
                </p.Stack>
              </p.Stack>

              <div className={classNames(projectcss.all, sty.column__hh7Dt)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__hisMq)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: illustrationBannerLuxuryGoodspngJkzxvrAAa,
                    fullWidth: 921,
                    fullHeight: 761,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"section1"}
            data-plasmic-override={overrides.section1}
            className={classNames(projectcss.all, sty.section1)}
          >
            <div className={classNames(projectcss.all, sty.columns__tLiO8)}>
              <div className={classNames(projectcss.all, sty.column__gr2Uz)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nZUs3
                  )}
                >
                  {
                    "Luxury goods companies provide products that are highly desired by customers. \n\nIn order to be successful, luxury goods companies must deliver a high-quality product as well as excellent customer service. \n\nHaving employees trained with proper etiquette and communication skills is a key component of success."
                  }
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oLvLl
                  )}
                >
                  {"HOW CAN THE INDUSTRY BENEFIT FROM USING COACH?"}
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__bHwql)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__puKmM)}
                  displayHeight={"282px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: luxury1Png2Lr73RiQs2,
                    fullWidth: 860,
                    fullHeight: 603,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"section2"}
            data-plasmic-override={overrides.section2}
            className={classNames(projectcss.all, sty.section2)}
          >
            <div className={classNames(projectcss.all, sty.columns___3P6Ru)}>
              <div className={classNames(projectcss.all, sty.column___3KJn8)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__riRgb)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"450px"}
                  loading={"lazy"}
                  src={{
                    src: webSalesTrainingpng70SZ9Vex,
                    fullWidth: 900,
                    fullHeight: 981,
                    aspectRatio: undefined
                  }}
                />
              </div>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__vljEz)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1Dckl
                  )}
                >
                  {"Sales Training"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zOkdf
                  )}
                >
                  {
                    "It is essential for employees to learn the proper way of providing customers with high-quality services. \n\nCoach provides training as well as assessment so that luxury goods companies can provide their employees and make them successful. \n\nCoach uses small bite-sized learning sessions, to make sure employees are able to improve their skills and become more successful individuals overall, without spending too much time off their work."
                  }
                </div>
              </p.Stack>
            </div>
          </div>

          <div
            data-plasmic-name={"section3"}
            data-plasmic-override={overrides.section3}
            className={classNames(projectcss.all, sty.section3)}
          >
            <div className={classNames(projectcss.all, sty.columns__yZd6K)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__ohgHt)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lbj7N
                  )}
                >
                  {"Product Training"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uudzv
                  )}
                >
                  {
                    "Knowing everything about the product you are selling is crucial if you want to position yourself as an expert. \n\nBy using Coach, each employee will be an expert regarding a certain product and provide customers with the correct information.\n\nCoach makes sure that product knowledge isn't forgotten and regularly refreshes the employee's knowledge. It's a quick and efficient way to ensure that you are always up-to-date with the newest products."
                  }
                </div>
              </p.Stack>

              <div className={classNames(projectcss.all, sty.column___1STlx)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__dI0Q)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"450px"}
                  loading={"lazy"}
                  src={{
                    src: webLuxuryProductpngIY87WaGni,
                    fullWidth: 901,
                    fullHeight: 981,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"section4"}
            data-plasmic-override={overrides.section4}
            className={classNames(projectcss.all, sty.section4)}
          >
            <div className={classNames(projectcss.all, sty.columns__bV8V1)}>
              <div className={classNames(projectcss.all, sty.column__fqkz1)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__nGdtx)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"450px"}
                  loading={"lazy"}
                  src={{
                    src: webCustomerRelationspng8IqsZVd7,
                    fullWidth: 900,
                    fullHeight: 981,
                    aspectRatio: undefined
                  }}
                />
              </div>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__rVbi1)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mIuI
                  )}
                >
                  {"Customer Relations Training"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uWaIx
                  )}
                >
                  {
                    "Coach helps employees connect with customers on a more personal level by improving their ability to provide positive experiences.\n\nCoach’s personalization algorithm makes every employee's experience unique, focusing on improving their weak points."
                  }
                </div>
              </p.Stack>
            </div>
          </div>

          <div
            data-plasmic-name={"section5"}
            data-plasmic-override={overrides.section5}
            className={classNames(projectcss.all, sty.section5)}
          >
            <div className={classNames(projectcss.all, sty.columns__pMeBp)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__emcbP)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yt836
                  )}
                >
                  {"Onboarding"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zuchW
                  )}
                >
                  {
                    "Getting new hires up to speed quickly is vital for any organization. \n\nEase the learning curve with a series of short microlearning training sessions that can be accessed at any time, and help new hires master your product in no time.\n\nIncrease productivity by learning when there are no customers around.\n"
                  }
                </div>
              </p.Stack>

              <div className={classNames(projectcss.all, sty.column__wTsml)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___2WMfX)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"450px"}
                  loading={"lazy"}
                  src={{
                    src: webOnboardingTrainingpng7WY11Mx3O,
                    fullWidth: 900,
                    fullHeight: 980,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </div>

          <p.Stack
            as={"div"}
            data-plasmic-name={"cta"}
            data-plasmic-override={overrides.cta}
            hasGap={true}
            className={classNames(projectcss.all, sty.cta)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__tj0St
              )}
            >
              {"READY TO START?"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__dCXo
              )}
            >
              {
                "Experience the full power of Coach in action, and see why microlearning is your company’s future."
              }
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___5Fwl5)}
            >
              <button
                className={classNames(
                  projectcss.all,
                  projectcss.button,
                  projectcss.__wab_text,
                  sty.button__rNkDm
                )}
              >
                {"BOOK A DEMO"}
              </button>

              <p.Stack
                as={"button"}
                hasGap={true}
                className={classNames(
                  projectcss.all,
                  projectcss.button,
                  sty.button___9VzC5
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rMmRe
                  )}
                >
                  {"GET STARTED"}
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__nmRiO)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"15px"}
                  loading={"lazy"}
                  src={{
                    src: buttonCaretWhitesvg2S5Jbv6HmTb,
                    fullWidth: 108,
                    fullHeight: 150,
                    aspectRatio: 0.722222
                  }}
                />
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "menuHeaderDesktop",
    "hero",
    "h1",
    "section1",
    "section2",
    "section3",
    "section4",
    "section5",
    "cta",
    "footer"
  ],

  menuHeaderDesktop: ["menuHeaderDesktop"],
  hero: ["hero", "h1"],
  h1: ["h1"],
  section1: ["section1"],
  section2: ["section2"],
  section3: ["section3"],
  section4: ["section4"],
  section5: ["section5"],
  cta: ["cta"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicIndustryLuxuryGoods__ArgProps,
          internalVariantPropNames: PlasmicIndustryLuxuryGoods__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicIndustryLuxuryGoods__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicIndustryLuxuryGoods";
  } else {
    func.displayName = `PlasmicIndustryLuxuryGoods.${nodeName}`;
  }
  return func;
}

export const PlasmicIndustryLuxuryGoods = Object.assign(
  // Top-level PlasmicIndustryLuxuryGoods renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    menuHeaderDesktop: makeNodeComponent("menuHeaderDesktop"),
    hero: makeNodeComponent("hero"),
    h1: makeNodeComponent("h1"),
    section1: makeNodeComponent("section1"),
    section2: makeNodeComponent("section2"),
    section3: makeNodeComponent("section3"),
    section4: makeNodeComponent("section4"),
    section5: makeNodeComponent("section5"),
    cta: makeNodeComponent("cta"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicIndustryLuxuryGoods
    internalVariantProps: PlasmicIndustryLuxuryGoods__VariantProps,
    internalArgProps: PlasmicIndustryLuxuryGoods__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicIndustryLuxuryGoods;
/* prettier-ignore-end */
