// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uu5v5CefeBFWJ3g58RuWZW
// Component: nmfZ_w1bFQh4
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import MenuHeaderDesktop from "../../MenuHeaderDesktop"; // plasmic-import: RhmfQLZ342T/component
import YellowButton from "../../YellowButton"; // plasmic-import: BW02p9J3E9/component
import Button from "../../Button"; // plasmic-import: i2u7Uturkgt/component
import Footer from "../../Footer"; // plasmic-import: 0UCZXj9Zumd/component
import { useScreenVariants as useScreenVariantsaAzWhvm6PjSv1 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: aAzWHVM6PJSv1/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_coach_website.module.css"; // plasmic-import: uu5v5CefeBFWJ3g58RuWZW/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: nmfZ_w1bFQh4/css
import CorrectsvgIcon from "./icons/PlasmicIcon__Correctsvg"; // plasmic-import: egZub56_e-/icon
import DownArrowIcon from "./icons/PlasmicIcon__DownArrow"; // plasmic-import: jcu2bb0zp/icon
import bannerimg1PngKTx7QbCd7 from "./images/bannerimg1Png.png"; // plasmic-import: KTx7QBCd7/picture
import group926SvgNM1517Ao from "./images/group926Svg.svg"; // plasmic-import: n_m1517ao/picture
import _1AddContentpngSG5QxGgnN from "./images/_1AddContentpng.png"; // plasmic-import: sG5QXGgnN/picture
import _2DeployAndPlaypngAvAnKfog from "./images/_2DeployAndPlaypng.png"; // plasmic-import: AvAn_Kfog/picture
import group925SvgC28AvbXr4 from "./images/group925Svg.svg"; // plasmic-import: C28AvbXR4/picture
import group924SvgHZ23I3Yn from "./images/group924Svg.svg"; // plasmic-import: H_Z23_I3yn/picture
import _3TrackAndImprovepngJaJlMKytt from "./images/_3TrackAndImprovepng.png"; // plasmic-import: JaJlMKytt/picture
import coachManagerssvgRqDhaxaBv from "./images/coachManagerssvg.svg"; // plasmic-import: RqDhaxaBV/picture
import coachSeossvgXSpyNpbVc from "./images/coachSeossvg.svg"; // plasmic-import: xSpyNpbVC/picture
import coachIdssvgXKnk6Mzl8 from "./images/coachIdssvg.svg"; // plasmic-import: xKNK6mzl8/picture
import coachEmployeessvgKtZvSgpX3 from "./images/coachEmployeessvg.svg"; // plasmic-import: ktZvSgpX3/picture
import group937Svg2IgFnzRrg from "./images/group937Svg.svg"; // plasmic-import: 2IgFnzRrg/picture
import x38Dxi29Tif1Svg4Oc4LE0 from "./images/x38Dxi29Tif1Svg.svg"; // plasmic-import: 4-Oc_4L-E0/picture
import group936SvgCq7W34IgVt from "./images/group936Svg.svg"; // plasmic-import: cq7W34igVt/picture
import industryIconsArtboard3Copy5SvgOFFgkBsf1 from "./images/industryIconsArtboard3Copy5Svg.svg"; // plasmic-import: oFFgkBSF1/picture
import industryIconsArtboard3Copy51SvgTeIaqtlIh from "./images/industryIconsArtboard3Copy51Svg.svg"; // plasmic-import: TEIaqtlIh/picture
import industryIconsArtboard3Copy52SvgYpGlw4Yg4 from "./images/industryIconsArtboard3Copy52Svg.svg"; // plasmic-import: ypGLW4YG4/picture
import industryIconsArtboard3Copy54SvgLUuagOb9N9 from "./images/industryIconsArtboard3Copy54Svg.svg"; // plasmic-import: lUUAGOb9n9/picture
import industryIconsArtboard3Copy53SvgIwDbQz7Mc3 from "./images/industryIconsArtboard3Copy53Svg.svg"; // plasmic-import: IwDbQZ7Mc3/picture
import _287StartupFlatlinesvgD9Kazplxb from "./images/_287StartupFlatlinesvg.svg"; // plasmic-import: d9Kazplxb/picture
import frame910JpgJ81OyBp4Q from "./images/frame910Jpg.jpeg"; // plasmic-import: j81oyBP4Q/picture
import frame909JpgEFUNZso from "./images/frame909Jpg.jpeg"; // plasmic-import: e_fU-nZso/picture
import frame908JpgI2W0HOkea from "./images/frame908Jpg.jpeg"; // plasmic-import: i2W0HOkea/picture

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array("whiteblueButton");

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsaAzWhvm6PjSv1()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root2"}
          data-plasmic-override={overrides.root2}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root2
          )}
        >
          <MenuHeaderDesktop
            data-plasmic-name={"menuHeaderDesktop"}
            data-plasmic-override={overrides.menuHeaderDesktop}
            className={classNames("__wab_instance", sty.menuHeaderDesktop)}
          />

          <p.Stack
            as={"div"}
            data-plasmic-name={"section1"}
            data-plasmic-override={overrides.section1}
            hasGap={true}
            className={classNames(projectcss.all, sty.section1)}
          >
            <div className={classNames(projectcss.all, sty.columns__oIjP6)}>
              <div className={classNames(projectcss.all, sty.column__n2TL5)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__wp57H)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"copy"}
                    data-plasmic-override={overrides.copy}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.copy)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__p0Fwk)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__k8Iol
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>

                          {
                            <h1
                              className={classNames(
                                projectcss.all,
                                projectcss.h1,
                                projectcss.__wab_text,
                                sty.h1__cadeT
                              )}
                            >
                              {"Effective Microlearning\nfor your employees."}
                            </h1>
                          }

                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lHxlJ
                        )}
                      >
                        {
                          "Coach helps you create and deliver personalized reinforcement training, fast."
                        }
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__swiwU)}
                    >
                      <YellowButton
                        data-plasmic-name={"yellowButton"}
                        data-plasmic-override={overrides.yellowButton}
                        className={classNames(
                          "__wab_instance",
                          sty.yellowButton
                        )}
                      />
                    </p.Stack>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iKefv
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>

                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000" }}
                          >
                            {"Do you already use Coach? "}
                          </span>

                          <React.Fragment>{"\n"}</React.Fragment>

                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000" }}
                          >
                            {""}
                          </span>

                          <React.Fragment>{""}</React.Fragment>

                          {
                            <a
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                projectcss.__wab_text,
                                projectcss.plasmic_default__inline,
                                sty.link__r2Ump
                              )}
                              href={"www.google.com"}
                            >
                              {hasVariant(
                                globalVariants,
                                "screen",
                                "mobileOnly"
                              )
                                ? "Sign in here."
                                : "Sign in here."}
                            </a>
                          }

                          <React.Fragment>{"\n"}</React.Fragment>
                        </React.Fragment>
                      ) : (
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>

                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000" }}
                          >
                            {"Do you already use Coach?"}
                          </span>

                          <React.Fragment>{"  "}</React.Fragment>

                          {
                            <a
                              className={classNames(
                                projectcss.all,
                                projectcss.a,
                                projectcss.__wab_text,
                                projectcss.plasmic_default__inline,
                                sty.link__r2Ump
                              )}
                              href={"www.google.com"}
                            >
                              {hasVariant(
                                globalVariants,
                                "screen",
                                "mobileOnly"
                              )
                                ? "Sign in here."
                                : "Sign in here."}
                            </a>
                          }

                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      )}
                    </div>
                  </p.Stack>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__h9Vh4)}>
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__w2HtN)}
                  />
                ) : null}

                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__mqe8C)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"320px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    src={{
                      src: bannerimg1PngKTx7QbCd7,
                      fullWidth: 1436,
                      fullHeight: 1410,
                      aspectRatio: undefined
                    }}
                  />
                ) : null}
              </div>
            </div>
          </p.Stack>

          <p.Stack
            as={"div"}
            data-plasmic-name={"section2"}
            data-plasmic-override={overrides.section2}
            hasGap={true}
            className={classNames(projectcss.all, sty.section2)}
          >
            <h1
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1__cym9A
              )}
            >
              {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                <React.Fragment>
                  <React.Fragment>
                    {"Gamify your learning experiences\n"}
                  </React.Fragment>

                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#3E7CB1" }}
                  >
                    {"with our powerful platform."}
                  </span>

                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              ) : (
                <React.Fragment>
                  <React.Fragment>
                    {"Gamify your learning experiences\n"}
                  </React.Fragment>

                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#3E7CB1" }}
                  >
                    {"with our powerful platform."}
                  </span>

                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              )}
            </h1>

            <div className={classNames(projectcss.all, sty.freeBox__a50Ht)} />
          </p.Stack>

          <div
            data-plasmic-name={"section3"}
            data-plasmic-override={overrides.section3}
            className={classNames(projectcss.all, sty.section3)}
          >
            <div className={classNames(projectcss.all, sty.column__b5V7D)}>
              <div className={classNames(projectcss.all, sty.freeBox__kInxN)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__wnIhx)}
                  displayHeight={"48px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"193px"}
                  loading={"lazy"}
                  src={{
                    src: group926SvgNM1517Ao,
                    fullWidth: 300,
                    fullHeight: 76,
                    aspectRatio: 3.959184
                  }}
                />

                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__ylo3G
                  )}
                >
                  {"Easy, fast and intuitive"}
                </h1>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oMgm2
                  )}
                >
                  {
                    "The process of digitalization of your trainings has never been easier until now - use our intuitive Admin panel to repurpose existing materials, create new ones, add asssesment questions and enable an efficient knowledge base for your employees."
                  }
                </div>

                <div
                  className={classNames(projectcss.all, sty.freeBox___1YATl)}
                >
                  <CorrectsvgIcon
                    className={classNames(projectcss.all, sty.svg__hgIw)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__g9Rl2
                    )}
                  >
                    {"LESSON & QUESTION BUILDER"}
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__ffaZy)}>
                  <CorrectsvgIcon
                    className={classNames(projectcss.all, sty.svg__fwkq)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xN4Ii
                    )}
                  >
                    {"IMPORTING AND STRUCTURING OPTIONS"}
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__cd9Fk)}>
                  <CorrectsvgIcon
                    className={classNames(projectcss.all, sty.svg__y2P72)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iYkBu
                    )}
                  >
                    {"ORGANIZED TOPICS BY TRAINING"}
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.column___9SqnS)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__lca4I)}
                displayHeight={"550px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"520px"}
                loading={"lazy"}
                src={{
                  src: _1AddContentpngSG5QxGgnN,
                  fullWidth: 1041,
                  fullHeight: 1100,
                  aspectRatio: undefined
                }}
              />
            </div>
          </div>

          <div
            data-plasmic-name={"section4"}
            data-plasmic-override={overrides.section4}
            className={classNames(projectcss.all, sty.section4)}
          >
            <div className={classNames(projectcss.all, sty.column__xclbb)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__geieu)}
                displayHeight={"550px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"520px"}
                loading={"lazy"}
                src={{
                  src: _2DeployAndPlaypngAvAnKfog,
                  fullWidth: 1041,
                  fullHeight: 1100,
                  aspectRatio: undefined
                }}
              />
            </div>

            <div className={classNames(projectcss.all, sty.column__qo7X)}>
              <div className={classNames(projectcss.all, sty.freeBox__j4Hho)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__qMPe)}
                  displayHeight={"48px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"199px"}
                  loading={"lazy"}
                  src={{
                    src: group925SvgC28AvbXr4,
                    fullWidth: 300,
                    fullHeight: 74,
                    aspectRatio: 4.081633
                  }}
                />

                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__cUsCr
                  )}
                >
                  {"Let the games begin"}
                </h1>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ifryj
                  )}
                >
                  {
                    "With our carefully crafted range of content-based interactive games, employees can swiftly refresh their knowledge and earn rewards. \nThe training process will never be boring again - are you ready to accept the challenge?"
                  }
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__s3LWk)}>
                  <CorrectsvgIcon
                    className={classNames(projectcss.all, sty.svg__lsw4)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ujPzc
                    )}
                  >
                    {"MOBILE-FIRST"}
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__hUj2R)}>
                  <CorrectsvgIcon
                    className={classNames(projectcss.all, sty.svg__zo0Ha)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__s6Ttm
                    )}
                  >
                    {"QUCIK & EFFECTIVE"}
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__q1LN3)}>
                  <CorrectsvgIcon
                    className={classNames(projectcss.all, sty.svg__sOJi)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lbTcK
                    )}
                  >
                    {"ENGAGING & CHALLENGING"}
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"section5"}
            data-plasmic-override={overrides.section5}
            className={classNames(projectcss.all, sty.section5)}
          >
            <div className={classNames(projectcss.all, sty.column___46Uf4)}>
              <div className={classNames(projectcss.all, sty.freeBox__xmamV)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__tBdse)}
                  displayHeight={"48px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"220px"}
                  loading={"lazy"}
                  src={{
                    src: group924SvgHZ23I3Yn,
                    fullWidth: 300,
                    fullHeight: 66,
                    aspectRatio: 4.530612
                  }}
                />

                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1___3F2BC
                  )}
                >
                  {"Get insights like never before"}
                </h1>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kLfv2
                  )}
                >
                  {
                    "Using our powerful analytics, you can easily generate a selection of valuable statistics and important KPIs, such as time to proficiency, knowledge meter, trainee satisfaction, progress over time, best-performing departments, employee strengths and weaknesses, and many more!"
                  }
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__vlNVo)}>
                  <CorrectsvgIcon
                    className={classNames(projectcss.all, sty.svg___3Fisd)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sAupz
                    )}
                  >
                    {"ORGANIZATION-WIDE INSIGHTS"}
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__gOryo)}>
                  <CorrectsvgIcon
                    className={classNames(projectcss.all, sty.svg__olhiN)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__agkb1
                    )}
                  >
                    {"DEPARTMENT LEVEL INSIGHTS"}
                  </div>
                </div>

                <div
                  className={classNames(projectcss.all, sty.freeBox___0KqUd)}
                >
                  <CorrectsvgIcon
                    className={classNames(projectcss.all, sty.svg___7AuQo)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__emvZz
                    )}
                  >
                    {"EMPLOYEE LEVEL INSIGHTS"}
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__mksYe)}>
                  {p.renderPlasmicSlot({
                    defaultContents: (
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__iPmlb
                        )}
                        endIcon={
                          <DownArrowIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__pbSu2
                            )}
                            role={"img"}
                          />
                        }
                        showEndIcon={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xvql
                          )}
                        >
                          {"Explore all features"}
                        </div>
                      </Button>
                    ),

                    value: args.whiteblueButton,
                    className: classNames(sty.slotTargetWhiteblueButton)
                  })}
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.column___0Qzs7)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___4MWjV)}
                displayHeight={"550px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"520px"}
                loading={"lazy"}
                src={{
                  src: _3TrackAndImprovepngJaJlMKytt,
                  fullWidth: 1041,
                  fullHeight: 1100,
                  aspectRatio: undefined
                }}
              />
            </div>
          </div>

          <p.Stack
            as={"div"}
            data-plasmic-name={"section6"}
            data-plasmic-override={overrides.section6}
            hasGap={true}
            className={classNames(projectcss.all, sty.section6)}
          >
            <h1
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1__zu9Yo
              )}
            >
              <React.Fragment>
                <React.Fragment>{"See how we can help you\n"}</React.Fragment>

                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#3E7CB1" }}
                >
                  {"transform the way knowledge is attained."}
                </span>

                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </h1>

            <div className={classNames(projectcss.all, sty.freeBox__ugWx2)} />
          </p.Stack>

          <p.Stack
            as={"div"}
            data-plasmic-name={"whoIsItFor"}
            data-plasmic-override={overrides.whoIsItFor}
            hasGap={true}
            className={classNames(projectcss.all, sty.whoIsItFor)}
          >
            <div className={classNames(projectcss.all, sty.column__vodF)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___6NM8R)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ccJbj)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"90%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: coachManagerssvgRqDhaxaBv,
                    fullWidth: 203,
                    fullHeight: 150,
                    aspectRatio: 1.354839
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nhYDv
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{"Coach for "}</React.Fragment>

                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#11253E", fontWeight: 700 }}
                    >
                      {"Managers"}
                    </span>

                    <React.Fragment>{"\n(HR, L&D, Training)"}</React.Fragment>
                  </React.Fragment>
                </div>
              </p.Stack>
            </div>

            <div className={classNames(projectcss.all, sty.column__vnlNh)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__dvsDu)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__hNnyv)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"90%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: coachSeossvgXSpyNpbVc,
                    fullWidth: 203,
                    fullHeight: 150,
                    aspectRatio: 1.354839
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__e0Bg
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{"Coach for "}</React.Fragment>

                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"CEO's"}
                    </span>

                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </p.Stack>
            </div>

            <div className={classNames(projectcss.all, sty.column__vdyY)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__dh104)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__vDo23)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"90%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: coachIdssvgXKnk6Mzl8,
                    fullWidth: 203,
                    fullHeight: 150,
                    aspectRatio: 1.354839
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qZ2Xx
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{"Coach for "}</React.Fragment>

                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"Instructional Designers"}
                    </span>

                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </p.Stack>
            </div>

            <div className={classNames(projectcss.all, sty.column__aBaNx)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___6X3Zb)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__tevHg)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"90%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: coachEmployeessvgKtZvSgpX3,
                    fullWidth: 203,
                    fullHeight: 150,
                    aspectRatio: 1.354839
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gEdD6
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{"Coach for "}</React.Fragment>

                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"Employees"}
                    </span>

                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </p.Stack>
            </div>
          </p.Stack>

          <div
            data-plasmic-name={"testimonial"}
            data-plasmic-override={overrides.testimonial}
            className={classNames(projectcss.all, sty.testimonial)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___5J7U7)} />

            <div className={classNames(projectcss.all, sty.columns__djeps)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__sf5Q9)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__uiZk8)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "auto"
                      : "88px"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "auto"
                      : "360px"
                  }
                  loading={"lazy"}
                  src={{
                    src: group937Svg2IgFnzRrg,
                    fullWidth: 300,
                    fullHeight: 74,
                    aspectRatio: 4.078652
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__v7Ndt)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__guFbY)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "none"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "25px"
                        : "57px"
                    }
                    loading={"lazy"}
                    src={{
                      src: x38Dxi29Tif1Svg4Oc4LE0,
                      fullWidth: 209,
                      fullHeight: 150,
                      aspectRatio: 1.390244
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yaDwO
                    )}
                  >
                    {"WHAT EXPERTS SAY"}
                  </div>
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__vyCo2)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "125px"
                      : "200px"
                  }
                  loading={"lazy"}
                  src={{
                    src: group936SvgCq7W34IgVt,
                    fullWidth: 104,
                    fullHeight: 150,
                    aspectRatio: 0.693431
                  }}
                />

                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__dukdB
                  )}
                >
                  {
                    "You've got an amazing product here and coming from someone who used to hard code Adobe Flash eLearning courses - it's a dream. "
                  }
                </h1>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__d4Frq
                  )}
                >
                  {"Nicholas Ashleigh"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cYfG5
                  )}
                >
                  {"15 years in L&D industry"}
                </div>
              </p.Stack>
            </div>
          </div>

          <p.Stack
            as={"div"}
            data-plasmic-name={"section7"}
            data-plasmic-override={overrides.section7}
            hasGap={true}
            className={classNames(projectcss.all, sty.section7)}
          >
            <h1
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1__mlcvr
              )}
            >
              <React.Fragment>
                <React.Fragment>{"Train employees in a wide\n"}</React.Fragment>

                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#3E7CB1" }}
                >
                  {"range of industries"}
                </span>

                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </h1>

            <div className={classNames(projectcss.all, sty.freeBox__shS54)} />
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns__hle8)}
          >
            <div className={classNames(projectcss.all, sty.column__zhUHb)}>
              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__pVz5C
                )}
              >
                <div className={classNames(projectcss.all, sty.freeBox__k4VxX)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__yiZ4O)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__rKqBe)}
                      displayHeight={"68px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"68px"}
                      loading={"lazy"}
                      src={{
                        src: industryIconsArtboard3Copy5SvgOFFgkBsf1,
                        fullWidth: 148,
                        fullHeight: 150,
                        aspectRatio: 0.985507
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4Xmqn
                      )}
                    >
                      {"Consumer Electronics"}
                    </div>
                  </p.Stack>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5ZocS
                    )}
                  >
                    {
                      "Aid your retail sales reps in mastering each detail in the product catalogue, easily onboard new hires and see how their professional confidence shines."
                    }
                  </div>
                </div>
              </a>
            </div>

            <div className={classNames(projectcss.all, sty.column__k95Eg)}>
              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__kjgMv
                )}
              >
                <div className={classNames(projectcss.all, sty.freeBox__jpT8X)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__qxvXh)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__uXggu)}
                      displayHeight={"68px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"68px"}
                      loading={"lazy"}
                      src={{
                        src: industryIconsArtboard3Copy51SvgTeIaqtlIh,
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fGMs
                      )}
                    >
                      {"Banking"}
                    </div>
                  </p.Stack>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bPePf
                    )}
                  >
                    {
                      "Aid your retail sales reps in mastering each detail in the product catalogue, easily onboard new hires and see how their professional confidence shines."
                    }
                  </div>
                </div>
              </a>
            </div>
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns__qngCr)}
          >
            <div className={classNames(projectcss.all, sty.column__z1Atp)}>
              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__iMkiP
                )}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___0Lbsi)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__b1TzJ)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__zA7GN)}
                      displayHeight={"68px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"68px"}
                      loading={"lazy"}
                      src={{
                        src: industryIconsArtboard3Copy52SvgYpGlw4Yg4,
                        fullWidth: 148,
                        fullHeight: 150,
                        aspectRatio: 0.985507
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iQb1O
                      )}
                    >
                      {"Telecommunications"}
                    </div>
                  </p.Stack>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__udxG6
                    )}
                  >
                    {
                      "Aid your retail sales reps in mastering each detail in the product catalogue, easily onboard new hires and see how their professional confidence shines."
                    }
                  </div>
                </div>
              </a>
            </div>

            <div className={classNames(projectcss.all, sty.column__cMzt)}>
              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__cDbsS
                )}
              >
                <div className={classNames(projectcss.all, sty.freeBox__jJmJi)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__voP67)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__jviMs)}
                      displayHeight={"68px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"68px"}
                      loading={"lazy"}
                      src={{
                        src: industryIconsArtboard3Copy5SvgOFFgkBsf1,
                        fullWidth: 148,
                        fullHeight: 150,
                        aspectRatio: 0.985507
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rN7Lt
                      )}
                    >
                      {"Manufacturing"}
                    </div>
                  </p.Stack>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__noZh
                    )}
                  >
                    {
                      "Help your manufacturing company build stronger bonds with your staff, and turn them into highly educated and adaptable workers."
                    }
                  </div>
                </div>
              </a>
            </div>
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns__slgLn)}
          >
            <div className={classNames(projectcss.all, sty.column__wIkDc)}>
              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__mRtlk
                )}
              >
                <div className={classNames(projectcss.all, sty.freeBox__kDBzA)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__lhDjJ)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__cetsZ)}
                      displayHeight={"68px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"68px"}
                      loading={"lazy"}
                      src={{
                        src: industryIconsArtboard3Copy54SvgLUuagOb9N9,
                        fullWidth: 148,
                        fullHeight: 150,
                        aspectRatio: 0.985507
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fAkyy
                      )}
                    >
                      {"Pharmaceuticals"}
                    </div>
                  </p.Stack>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ip7De
                    )}
                  >
                    {
                      "Effortlessly train your sales reps to be up-to-date with FDA requirements, market demands, new products, and legal drug guidelines at all times."
                    }
                  </div>
                </div>
              </a>
            </div>

            <div className={classNames(projectcss.all, sty.column__wq8Lw)}>
              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__wiQmp
                )}
              >
                <div className={classNames(projectcss.all, sty.freeBox__rQwjc)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__suR1L)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___2DsPc)}
                      displayHeight={"68px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"68px"}
                      loading={"lazy"}
                      src={{
                        src: industryIconsArtboard3Copy53SvgIwDbQz7Mc3,
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xzEx
                      )}
                    >
                      {"Luxury Goods"}
                    </div>
                  </p.Stack>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__z1Jg
                    )}
                  >
                    {
                      "Ensure your employees exceed in selling highly attractive products and maintaining valuable customer relations."
                    }
                  </div>
                </div>
              </a>
            </div>
          </p.Stack>

          <div className={classNames(projectcss.all, sty.freeBox__sCvlg)} />

          <div
            data-plasmic-name={"ctaBlog"}
            data-plasmic-override={overrides.ctaBlog}
            className={classNames(projectcss.all, sty.ctaBlog)}
          >
            <div className={classNames(projectcss.all, sty.columns__kd2Ke)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__zKan)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wTRgl
                  )}
                >
                  {"READY TO START?"}
                </div>

                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__m0W9O
                  )}
                >
                  {
                    "Experience the full power of Coach in action, and see why microlearning \nis your company’s future."
                  }
                </h1>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__zkhM1)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"270px"}
                  loading={"lazy"}
                  src={{
                    src: _287StartupFlatlinesvgD9Kazplxb,
                    fullWidth: 173,
                    fullHeight: 150,
                    aspectRatio: 1.155172
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__j39Oy)}>
                  <button
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      projectcss.__wab_text,
                      sty.button__qzP
                    )}
                  >
                    {"BOOK A DEMO"}
                  </button>

                  <button
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      projectcss.__wab_text,
                      sty.button__p3WIh
                    )}
                  >
                    {"GET STARTED"}
                  </button>
                </div>
              </p.Stack>
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"section9"}
              data-plasmic-override={overrides.section9}
              hasGap={true}
              className={classNames(projectcss.all, sty.section9)}
            >
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__eMweZ
                )}
              >
                {"Our latest news and resources"}
              </h1>

              <div className={classNames(projectcss.all, sty.freeBox__dU6Tl)} />
            </p.Stack>

            <div className={classNames(projectcss.all, sty.columns__uUosY)}>
              <div className={classNames(projectcss.all, sty.column___00FKz)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xGpMy)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___2Bps)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: frame910JpgJ81OyBp4Q,
                      fullWidth: 323,
                      fullHeight: 203,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4CVy
                    )}
                  >
                    {"PRESS ARTICLE"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__c7Pci
                    )}
                  >
                    {"Konceptiva: startup of the month January ’22!"}
                  </div>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__by9CQ)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__n0Oec)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__k8Dr)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: frame909JpgEFUNZso,
                      fullWidth: 323,
                      fullHeight: 203,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__t3GLc
                    )}
                  >
                    {"EVENT"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yhFpt
                    )}
                  >
                    {"Gamification of Corporate\nTraining - #Session1"}
                  </div>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__wtKHb)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__hf6Pd)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__lz7Ve)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: frame908JpgI2W0HOkea,
                      fullWidth: 323,
                      fullHeight: 203,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cQ0P
                    )}
                  >
                    {"BLOG"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wjfPx
                    )}
                  >
                    {"Here are 5 tips for creating\nan effective course"}
                  </div>
                </p.Stack>
              </div>
            </div>
          </div>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root2: [
    "root2",
    "menuHeaderDesktop",
    "section1",
    "copy",
    "yellowButton",
    "section2",
    "section3",
    "section4",
    "section5",
    "section6",
    "whoIsItFor",
    "testimonial",
    "section7",
    "ctaBlog",
    "section9",
    "footer"
  ],

  menuHeaderDesktop: ["menuHeaderDesktop"],
  section1: ["section1", "copy", "yellowButton"],
  copy: ["copy", "yellowButton"],
  yellowButton: ["yellowButton"],
  section2: ["section2"],
  section3: ["section3"],
  section4: ["section4"],
  section5: ["section5"],
  section6: ["section6"],
  whoIsItFor: ["whoIsItFor"],
  testimonial: ["testimonial"],
  section7: ["section7"],
  ctaBlog: ["ctaBlog", "section9"],
  section9: ["section9"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root2") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root2"),
  {
    // Helper components rendering sub-elements
    menuHeaderDesktop: makeNodeComponent("menuHeaderDesktop"),
    section1: makeNodeComponent("section1"),
    copy: makeNodeComponent("copy"),
    yellowButton: makeNodeComponent("yellowButton"),
    section2: makeNodeComponent("section2"),
    section3: makeNodeComponent("section3"),
    section4: makeNodeComponent("section4"),
    section5: makeNodeComponent("section5"),
    section6: makeNodeComponent("section6"),
    whoIsItFor: makeNodeComponent("whoIsItFor"),
    testimonial: makeNodeComponent("testimonial"),
    section7: makeNodeComponent("section7"),
    ctaBlog: makeNodeComponent("ctaBlog"),
    section9: makeNodeComponent("section9"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
