// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uu5v5CefeBFWJ3g58RuWZW
// Component: BnI8QqbLFB1
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import ReusableHeader from "../../ReusableHeader"; // plasmic-import: OcmELIHcZf/component
import Footer from "../../Footer"; // plasmic-import: 0UCZXj9Zumd/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_coach_website.module.css"; // plasmic-import: uu5v5CefeBFWJ3g58RuWZW/projectcss
import sty from "./PlasmicIndustryConsumerElectronics.module.css"; // plasmic-import: BnI8QqbLFB1/css
import industryIconsConsumerelectronicspngLywdoMcQp from "./images/industryIconsConsumerelectronicspng.png"; // plasmic-import: LYWDOMcQp/picture
import buttonCaretWhitesvg2S5Jbv6HmTb from "./images/buttonCaretWhitesvg2.svg"; // plasmic-import: S5jbv6HmTb/picture
import illustrationBannerConsumerElectronicspngDPkLBpuo from "./images/illustrationBannerConsumerElectronicspng.png"; // plasmic-import: DPkL_BPUO/picture
import crookedBg3SvgH1G7EkiWgx from "./images/crookedBg3Svg.svg"; // plasmic-import: h1G7ekiWgx/picture
import consumerelectronics1Png2J4UC9Ex4V from "./images/consumerelectronics1Png2.png"; // plasmic-import: J4uC9Ex4V/picture
import webOnboardingTrainingpng7WY11Mx3O from "./images/webOnboardingTrainingpng.png"; // plasmic-import: 7wY11MX3O/picture
import crookedBg4SvgXJa9D6Q77 from "./images/crookedBg4Svg.svg"; // plasmic-import: xJA9D6q77/picture
import webConsumerProductpng2UHzpz2V0M from "./images/webConsumerProductpng2.png"; // plasmic-import: uHzpz2V0M/picture
import webSoftskillsTrainingpngNrfAsd9HE from "./images/webSoftskillsTrainingpng.png"; // plasmic-import: nrfASD9hE/picture

export const PlasmicIndustryConsumerElectronics__VariantProps = new Array();

export const PlasmicIndustryConsumerElectronics__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicIndustryConsumerElectronics__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__af8Ef)} />

          <ReusableHeader
            data-plasmic-name={"reusableHeader"}
            data-plasmic-override={overrides.reusableHeader}
            className={classNames("__wab_instance", sty.reusableHeader)}
          />

          <div
            data-plasmic-name={"hero"}
            data-plasmic-override={overrides.hero}
            className={classNames(projectcss.all, sty.hero)}
          >
            <div className={classNames(projectcss.all, sty.columns__qkAe)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__zWkp8)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__isxDm)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__zQtR5)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__veFq3)}
                      displayHeight={"35px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"35px"}
                      loading={"lazy"}
                      src={{
                        src: industryIconsConsumerelectronicspngLywdoMcQp,
                        fullWidth: 225,
                        fullHeight: 225,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tyjTc
                      )}
                    >
                      {"COACH FOR CONSUMER ELECTRONICS"}
                    </div>
                  </p.Stack>

                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#11253E" }}
                      >
                        {"Employee training for"}
                      </span>

                      <React.Fragment>{"\n"}</React.Fragment>

                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#3E7CB1" }}
                      >
                        {"Consumer Electronics"}
                      </span>
                    </React.Fragment>
                  </h1>
                </p.Stack>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qExU4
                  )}
                >
                  {
                    "Aid your retail sales reps in mastering each detail in the product catalogue, easily onboard new hires and see how their professional confidence shines."
                  }
                </div>

                <p.Stack
                  as={"button"}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.button,
                    sty.button__fl2Iw
                  )}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__glbi4
                    )}
                  >
                    {"BOOK A DEMO"}
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__y7UmT)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"15px"}
                    loading={"lazy"}
                    src={{
                      src: buttonCaretWhitesvg2S5Jbv6HmTb,
                      fullWidth: 108,
                      fullHeight: 150,
                      aspectRatio: 0.722222
                    }}
                  />
                </p.Stack>
              </p.Stack>

              <div className={classNames(projectcss.all, sty.column__vSuxt)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__plUgg)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: illustrationBannerConsumerElectronicspngDPkLBpuo,
                    fullWidth: 921,
                    fullHeight: 761,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </div>

          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img___7FhC9)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: crookedBg3SvgH1G7EkiWgx,
              fullWidth: 300,
              fullHeight: 14,
              aspectRatio: 20.869565
            }}
          />

          <div
            data-plasmic-name={"section1"}
            data-plasmic-override={overrides.section1}
            className={classNames(projectcss.all, sty.section1)}
          >
            <div className={classNames(projectcss.all, sty.columns__pkFyD)}>
              <div className={classNames(projectcss.all, sty.column__k8Aeg)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wwYEq
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>
                      {
                        "Employees in consumer electronics are sometimes required to master hundreds, if not thousands of products. \nConstant updates and additions to product catalogues, make this process difficult for everyone from the HR & Training department all the way to the trainees.\n\nThis process becomes especially difficult when onboarding new hires, as bombarding them with information about thousands of products is a guaranteed way to overwhelm and confuse them.\n\nThe largest problem is when companies provide inefficient or no training at all. Inefficient training leads to lost sales opportunities, bad customer reviews and overall negative employee experience.\n\n"
                      }
                    </React.Fragment>

                    {
                      <h4
                        data-plasmic-name={"h4"}
                        data-plasmic-override={overrides.h4}
                        className={classNames(
                          projectcss.all,
                          projectcss.h4,
                          projectcss.__wab_text,
                          sty.h4
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>
                            {"The good news is that there is a "}
                          </React.Fragment>

                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#FEBE10", fontWeight: 700 }}
                          >
                            {"solution"}
                          </span>

                          <React.Fragment>{"."}</React.Fragment>
                        </React.Fragment>
                      </h4>
                    }

                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sSuYi
                  )}
                >
                  {"HOW CAN THE INDUSTRY BENEFIT FROM USING COACH?"}
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__ghAI)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__fJ2Hk)}
                  displayHeight={"282px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: consumerelectronics1Png2J4UC9Ex4V,
                    fullWidth: 860,
                    fullHeight: 601,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"section2"}
            data-plasmic-override={overrides.section2}
            className={classNames(projectcss.all, sty.section2)}
          >
            <div className={classNames(projectcss.all, sty.columns__qaA2U)}>
              <div className={classNames(projectcss.all, sty.column___4TJjj)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__eRkzG)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"450px"}
                  loading={"lazy"}
                  src={{
                    src: webOnboardingTrainingpng7WY11Mx3O,
                    fullWidth: 900,
                    fullHeight: 980,
                    aspectRatio: undefined
                  }}
                />
              </div>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___1SFm)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pK2Pl
                  )}
                >
                  {"Onboard new hires on \n1000’s of products"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8FfsS
                  )}
                >
                  {
                    "Getting new hires up to speed quickly is vital for any organization. \n\nEase the learning curve with a series of short microlearning training sessions that can be accessed at any time, and help new hires master your product catalog in no time.\n\nIncrease productivity by learning when there are no customers around.\n"
                  }
                </div>
              </p.Stack>
            </div>
          </div>

          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__ekM9)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: crookedBg4SvgXJa9D6Q77,
              fullWidth: 300,
              fullHeight: 14,
              aspectRatio: 20.869565
            }}
          />

          <div
            data-plasmic-name={"section3"}
            data-plasmic-override={overrides.section3}
            className={classNames(projectcss.all, sty.section3)}
          >
            <div className={classNames(projectcss.all, sty.columns___4Zi1N)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__mn9Ge)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8PmsG
                  )}
                >
                  {"Master Product Knowledge"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ljVf8
                  )}
                >
                  {
                    "Providing product training materials often isn't enough for employees to master the product.\n\nThis is where Coach excels.\nLearn every detail about your products through the learning section and then test your knowledge through our 8 interactive games.\n\nThe best thing is - employees will only need 5-6 minutes daily to master your product catalog."
                  }
                </div>
              </p.Stack>

              <div className={classNames(projectcss.all, sty.column__rTv4W)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___0FjCk)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"450px"}
                  loading={"lazy"}
                  src={{
                    src: webConsumerProductpng2UHzpz2V0M,
                    fullWidth: 901,
                    fullHeight: 981,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </div>

          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__h1U9W)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: crookedBg3SvgH1G7EkiWgx,
              fullWidth: 300,
              fullHeight: 14,
              aspectRatio: 20.869565
            }}
          />

          <div
            data-plasmic-name={"section4"}
            data-plasmic-override={overrides.section4}
            className={classNames(projectcss.all, sty.section4)}
          >
            <div className={classNames(projectcss.all, sty.columns__spoFd)}>
              <div className={classNames(projectcss.all, sty.column__kvC1C)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___36668)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"450px"}
                  loading={"lazy"}
                  src={{
                    src: webSoftskillsTrainingpngNrfAsd9HE,
                    fullWidth: 901,
                    fullHeight: 981,
                    aspectRatio: undefined
                  }}
                />
              </div>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__jiWv3)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__owj58
                  )}
                >
                  {"Increase Sales Effectiveness"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__he23A
                  )}
                >
                  {
                    "In retail, confidence, knowledge, and experience levels vary a lot between employees. \n\nYou need your employees to not only get the grips with the product's specifications but also be able to make a connection and empathize with your customers to be able to close a sale. \n\nWith Coach, you can easily create training that will boost employees' knowledge and skills, as well as refresh what they already learned."
                  }
                </div>
              </p.Stack>
            </div>
          </div>

          <p.Stack
            as={"div"}
            data-plasmic-name={"cta2"}
            data-plasmic-override={overrides.cta2}
            hasGap={true}
            className={classNames(projectcss.all, sty.cta2)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__e3Nw
              )}
            >
              {"READY TO START?"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__tUtXy
              )}
            >
              {
                "Experience the full power of Coach in action, and see why microlearning is your company’s future."
              }
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__uyLLo)}
            >
              <p.Stack
                as={"button"}
                hasGap={true}
                className={classNames(
                  projectcss.all,
                  projectcss.button,
                  sty.button__m2Oaf
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8DM6Y
                  )}
                >
                  {"GET STARTED"}
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__gqIt)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"15px"}
                  loading={"lazy"}
                  src={{
                    src: buttonCaretWhitesvg2S5Jbv6HmTb,
                    fullWidth: 108,
                    fullHeight: 150,
                    aspectRatio: 0.722222
                  }}
                />
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "reusableHeader",
    "hero",
    "h1",
    "section1",
    "h4",
    "section2",
    "section3",
    "section4",
    "cta2",
    "footer"
  ],

  reusableHeader: ["reusableHeader"],
  hero: ["hero", "h1"],
  h1: ["h1"],
  section1: ["section1", "h4"],
  h4: ["h4"],
  section2: ["section2"],
  section3: ["section3"],
  section4: ["section4"],
  cta2: ["cta2"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicIndustryConsumerElectronics__ArgProps,
          internalVariantPropNames:
            PlasmicIndustryConsumerElectronics__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicIndustryConsumerElectronics__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicIndustryConsumerElectronics";
  } else {
    func.displayName = `PlasmicIndustryConsumerElectronics.${nodeName}`;
  }
  return func;
}

export const PlasmicIndustryConsumerElectronics = Object.assign(
  // Top-level PlasmicIndustryConsumerElectronics renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    reusableHeader: makeNodeComponent("reusableHeader"),
    hero: makeNodeComponent("hero"),
    h1: makeNodeComponent("h1"),
    section1: makeNodeComponent("section1"),
    h4: makeNodeComponent("h4"),
    section2: makeNodeComponent("section2"),
    section3: makeNodeComponent("section3"),
    section4: makeNodeComponent("section4"),
    cta2: makeNodeComponent("cta2"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicIndustryConsumerElectronics
    internalVariantProps: PlasmicIndustryConsumerElectronics__VariantProps,
    internalArgProps: PlasmicIndustryConsumerElectronics__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicIndustryConsumerElectronics;
/* prettier-ignore-end */
