// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uu5v5CefeBFWJ3g58RuWZW
// Component: 0UdrnE_GFOJ
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import MenuHeaderDesktop from "../../MenuHeaderDesktop"; // plasmic-import: RhmfQLZ342T/component
import Footer from "../../Footer"; // plasmic-import: 0UCZXj9Zumd/component
import { useScreenVariants as useScreenVariantsaAzWhvm6PjSv1 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: aAzWHVM6PJSv1/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_coach_website.module.css"; // plasmic-import: uu5v5CefeBFWJ3g58RuWZW/projectcss
import sty from "./PlasmicIndustryPharmaceuticals.module.css"; // plasmic-import: 0UdrnE_GFOJ/css
import illustrationBannerPharmapng0KhpcwPYb from "./images/illustrationBannerPharmapng.png"; // plasmic-import: 0KhpcwPYb/picture
import group1041SvgDaac1Uz from "./images/group1041Svg.svg"; // plasmic-import: Daac1-_Uz-/picture
import webPharmaProductTrainingpngEvq4OZhow from "./images/webPharmaProductTrainingpng.png"; // plasmic-import: EVQ4oZHOW/picture
import webManufacturingSafetypngJ36Q0EyCx from "./images/webManufacturingSafetypng.png"; // plasmic-import: J36q0EyCx/picture
import webOnboardingTrainingpng7WY11Mx3O from "./images/webOnboardingTrainingpng.png"; // plasmic-import: 7wY11MX3O/picture
import webPharmaResearchpngFMzADzZb from "./images/webPharmaResearchpng.png"; // plasmic-import: fMZ_ADzZb/picture

export const PlasmicIndustryPharmaceuticals__VariantProps = new Array();

export const PlasmicIndustryPharmaceuticals__ArgProps = new Array();

function PlasmicIndustryPharmaceuticals__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsaAzWhvm6PjSv1()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <MenuHeaderDesktop
            data-plasmic-name={"menuHeaderDesktop"}
            data-plasmic-override={overrides.menuHeaderDesktop}
            className={classNames("__wab_instance", sty.menuHeaderDesktop)}
          />

          <div
            data-plasmic-name={"hero"}
            data-plasmic-override={overrides.hero}
            className={classNames(projectcss.all, sty.hero)}
          >
            <div className={classNames(projectcss.all, sty.columns___0Ej6)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__vEqRu)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vQJy7
                  )}
                >
                  {"COACH FOR PHARMA COMPANIES"}
                </div>

                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                    <React.Fragment>
                      <React.Fragment>
                        {"Employee training in\n"}
                      </React.Fragment>

                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#3E7CB1" }}
                      >
                        {"Pharmaceutical companies"}
                      </span>

                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  ) : (
                    <React.Fragment>
                      <React.Fragment>
                        {"Employee training in\n"}
                      </React.Fragment>

                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#3E7CB1" }}
                      >
                        {"Pharmaceutical companies"}
                      </span>

                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  )}
                </h1>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iRvaE
                  )}
                >
                  {
                    "Effortlessly train your sales reps to be up-to-date with FDA requirements, market demands, new products and legal drug guidelines at all times."
                  }
                </div>

                <button
                  className={classNames(
                    projectcss.all,
                    projectcss.button,
                    projectcss.__wab_text,
                    sty.button__jmPi1
                  )}
                >
                  {"BOOK A DEMO"}
                </button>
              </p.Stack>

              <div className={classNames(projectcss.all, sty.column__gWhOg)}>
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__tXCz)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: illustrationBannerPharmapng0KhpcwPYb,
                      fullWidth: 921,
                      fullHeight: 760,
                      aspectRatio: undefined
                    }}
                  />
                ) : null}
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"section1"}
            data-plasmic-override={overrides.section1}
            className={classNames(projectcss.all, sty.section1)}
          >
            <div className={classNames(projectcss.all, sty.columns__gIrZn)}>
              <div className={classNames(projectcss.all, sty.column___5WSMn)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wVv
                  )}
                >
                  {
                    "It's important for pharmaceutical companies to provide their staff with adequate training in order improve how best they can serve customers. Coach can assist them in seeing exactly where their new employees are at in the training process and help them when they are struggling with different product concepts or compliance issues. This way the companies save time and money while reducing the possibility of any compliance issues."
                  }
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6K1Im
                  )}
                >
                  {"HOW CAN THE INDUSTRY BENEFIT FROM USING COACH?"}
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column___9Dfsk)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__dY6Kt)}
                  displayHeight={"282px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: group1041SvgDaac1Uz,
                    fullWidth: 263,
                    fullHeight: 150,
                    aspectRatio: 1.752941
                  }}
                />
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"section2"}
            data-plasmic-override={overrides.section2}
            className={classNames(projectcss.all, sty.section2)}
          >
            <div className={classNames(projectcss.all, sty.columns__vJJr3)}>
              <div className={classNames(projectcss.all, sty.column__yuUHf)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__uqGa0)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: webPharmaProductTrainingpngEvq4OZhow,
                    fullWidth: 901,
                    fullHeight: 980,
                    aspectRatio: undefined
                  }}
                />
              </div>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__cU9Nq)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yPmT
                  )}
                >
                  {"Product Training Programs"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jqCi
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>
                      {
                        "Pharmaceutical sales reps are the main link between pharmaceutical companies and physicians. This makes it even more important to ensure they have in-depth product knowledge that is up to date with FDA requirements, market demands, and legal guidelines at all times! \n\n"
                      }
                    </React.Fragment>

                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"Coach "}
                    </span>

                    <React.Fragment>
                      {
                        "lets you create and distribute training programs that can be used to keep your product knowledge up-to-date. The content creation tool lets you create lessons about specific products and deploy them easily. Create as many programs as you need for one position, specific departments, or the whole company!  "
                      }
                    </React.Fragment>
                  </React.Fragment>
                </div>
              </p.Stack>
            </div>
          </div>

          <div
            data-plasmic-name={"section3"}
            data-plasmic-override={overrides.section3}
            className={classNames(projectcss.all, sty.section3)}
          >
            <div className={classNames(projectcss.all, sty.columns__qp0Mz)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__tVt7N)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kNoGp
                  )}
                >
                  {"Workplace Safety and\nMachine Handling"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ltwN0
                  )}
                >
                  {
                    "It’s critical for everyone to know all the safety standards set forth by the industry they work in and what’s required when working around these materials.\n\nThe problem with workplace safety training is that it gets quickly forgotten and it is not being refreshed enough for both new and current employees. (It is scientifically proven that 70% of the knowledge we learn, gets forgotten after a week).\n\nCoach's scientifically proven methods such as spaced repetition, combined with interactive games and gamification methods increase knowledge retention and battle the forgetting curve. Coach gets everyone be up to date with the latest safety standards, and lets them refresh their knowledge every week by spending short amounts of time playing fun games!"
                  }
                </div>
              </p.Stack>

              <div className={classNames(projectcss.all, sty.column__jUwhf)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___6Y9L2)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: webManufacturingSafetypngJ36Q0EyCx,
                    fullWidth: 900,
                    fullHeight: 980,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"section4"}
            data-plasmic-override={overrides.section4}
            className={classNames(projectcss.all, sty.section4)}
          >
            <div className={classNames(projectcss.all, sty.columns__vTh7)}>
              <div className={classNames(projectcss.all, sty.column__scbK9)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___7NxKo)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: webOnboardingTrainingpng7WY11Mx3O,
                    fullWidth: 900,
                    fullHeight: 980,
                    aspectRatio: undefined
                  }}
                />
              </div>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__pF1IX)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kpbh1
                  )}
                >
                  {"Employee Onboarding"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1UdSu
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>
                      {
                        "Pharmaceutical companies have a great number of new employees joining their companies every year.  It can be a difficult task to onboard new employees in the pharmaceutical industry because of all the compliance training that is required.\n\n"
                      }
                    </React.Fragment>

                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"Coach"}
                    </span>

                    <React.Fragment>
                      {
                        " can help pharmaceutical companies onboard employees faster and more effectively!"
                      }
                    </React.Fragment>
                  </React.Fragment>
                </div>
              </p.Stack>
            </div>
          </div>

          <div
            data-plasmic-name={"section5"}
            data-plasmic-override={overrides.section5}
            className={classNames(projectcss.all, sty.section5)}
          >
            <div className={classNames(projectcss.all, sty.columns__h3ADz)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___6Nk6A)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__v5O86
                  )}
                >
                  {"Research and development \ntraining"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xLagx
                  )}
                >
                  {
                    "Pharmaceutical companies want their employees working in the R&D department to be knowledgeable about the latest drug therapies, how to develop new drugs and how to bring them through clinical trials.\n\nMany of the LMS systems are not customizable and the content that they provide can be inadequate for the training needed. This is why Coach has a built-in content creation tool which can help with the customization of the training programs.\n\nThe microlearning methodology that Coach uses provides short chunks of information to make sure that employees are not overwhelmed. "
                  }
                </div>
              </p.Stack>

              <div className={classNames(projectcss.all, sty.column___66PMu)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__erzZz)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: webPharmaResearchpngFMzADzZb,
                    fullWidth: 901,
                    fullHeight: 980,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </div>

          <p.Stack
            as={"div"}
            data-plasmic-name={"cta"}
            data-plasmic-override={overrides.cta}
            hasGap={true}
            className={classNames(projectcss.all, sty.cta)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nwFyZ
              )}
            >
              {"READY TO START?"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nFztF
              )}
            >
              {
                "Experience the full power of Coach in action, and see why microlearning is your company’s future."
              }
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"freeBox"}
              data-plasmic-override={overrides.freeBox}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox)}
            >
              <button
                className={classNames(
                  projectcss.all,
                  projectcss.button,
                  projectcss.__wab_text,
                  sty.button___5W3Xw
                )}
              >
                {"BOOK A DEMO"}
              </button>

              <button
                className={classNames(
                  projectcss.all,
                  projectcss.button,
                  projectcss.__wab_text,
                  sty.button___31Zzw
                )}
              >
                {"GET STARTED"}
              </button>
            </p.Stack>
          </p.Stack>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "menuHeaderDesktop",
    "hero",
    "h1",
    "section1",
    "section2",
    "section3",
    "section4",
    "section5",
    "cta",
    "freeBox",
    "footer"
  ],

  menuHeaderDesktop: ["menuHeaderDesktop"],
  hero: ["hero", "h1"],
  h1: ["h1"],
  section1: ["section1"],
  section2: ["section2"],
  section3: ["section3"],
  section4: ["section4"],
  section5: ["section5"],
  cta: ["cta", "freeBox"],
  freeBox: ["freeBox"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicIndustryPharmaceuticals__ArgProps,
          internalVariantPropNames: PlasmicIndustryPharmaceuticals__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicIndustryPharmaceuticals__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicIndustryPharmaceuticals";
  } else {
    func.displayName = `PlasmicIndustryPharmaceuticals.${nodeName}`;
  }
  return func;
}

export const PlasmicIndustryPharmaceuticals = Object.assign(
  // Top-level PlasmicIndustryPharmaceuticals renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    menuHeaderDesktop: makeNodeComponent("menuHeaderDesktop"),
    hero: makeNodeComponent("hero"),
    h1: makeNodeComponent("h1"),
    section1: makeNodeComponent("section1"),
    section2: makeNodeComponent("section2"),
    section3: makeNodeComponent("section3"),
    section4: makeNodeComponent("section4"),
    section5: makeNodeComponent("section5"),
    cta: makeNodeComponent("cta"),
    freeBox: makeNodeComponent("freeBox"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicIndustryPharmaceuticals
    internalVariantProps: PlasmicIndustryPharmaceuticals__VariantProps,
    internalArgProps: PlasmicIndustryPharmaceuticals__ArgProps
  }
);

export default PlasmicIndustryPharmaceuticals;
/* prettier-ignore-end */
