// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uu5v5CefeBFWJ3g58RuWZW
// Component: rM_3tFwMIBc
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import MenuHeaderDesktop from "../../MenuHeaderDesktop"; // plasmic-import: RhmfQLZ342T/component
import Footer from "../../Footer"; // plasmic-import: 0UCZXj9Zumd/component
import { useScreenVariants as useScreenVariantsaAzWhvm6PjSv1 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: aAzWHVM6PJSv1/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_coach_website.module.css"; // plasmic-import: uu5v5CefeBFWJ3g58RuWZW/projectcss
import sty from "./PlasmicWhoIsItForEmployees.module.css"; // plasmic-import: rM_3tFwMIBc/css
import coachEmployeessvgKtZvSgpX3 from "./images/coachEmployeessvg.svg"; // plasmic-import: ktZvSgpX3/picture
import webEmployees1PngTw3RXaUv7 from "./images/webEmployees1Png.png"; // plasmic-import: Tw3rXaUv7/picture
import webEmployees2Png3CSoMm4Uh from "./images/webEmployees2Png.png"; // plasmic-import: 3CSoMm4uh/picture
import webEmployees3Png1RI9KuqTz from "./images/webEmployees3Png.png"; // plasmic-import: 1rI9KUQTz/picture
import webEmployees4PngTQlJi9Cl3 from "./images/webEmployees4Png.png"; // plasmic-import: TQlJi9Cl3/picture
import phoneCutEmployeespngIt31Wkx6U from "./images/phoneCutEmployeespng.png"; // plasmic-import: It31wkx6U/picture

export const PlasmicWhoIsItForEmployees__VariantProps = new Array();

export const PlasmicWhoIsItForEmployees__ArgProps = new Array();

function PlasmicWhoIsItForEmployees__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsaAzWhvm6PjSv1()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <MenuHeaderDesktop
            data-plasmic-name={"menuHeaderDesktop"}
            data-plasmic-override={overrides.menuHeaderDesktop}
            className={classNames("__wab_instance", sty.menuHeaderDesktop)}
          />

          <p.Stack
            as={"div"}
            data-plasmic-name={"hero"}
            data-plasmic-override={overrides.hero}
            hasGap={true}
            className={classNames(projectcss.all, sty.hero)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__b83L8
              )}
            >
              {"COACH FOR EMPLOYEES"}
            </div>

            <h1
              data-plasmic-name={"h1"}
              data-plasmic-override={overrides.h1}
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1
              )}
            >
              {hasVariant(globalVariants, "screen", "mobileOnly")
                ? "The training tool \nthat helps you learn"
                : "The training tool that\nactually helps you learn"}
            </h1>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qDiun
              )}
            >
              {"Try out Coach and make sure your manager knows about it!"}
            </div>

            <button
              className={classNames(
                projectcss.all,
                projectcss.button,
                projectcss.__wab_text,
                sty.button__gWcRi
              )}
            >
              {"GET STARTED"}
            </button>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__ftMoO)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"263px"}
              loading={"lazy"}
              src={{
                src: coachEmployeessvgKtZvSgpX3,
                fullWidth: 203,
                fullHeight: 150,
                aspectRatio: 1.354839
              }}
            />
          </p.Stack>

          <div className={classNames(projectcss.all, sty.freeBox__fGrf8)}>
            <div className={classNames(projectcss.all, sty.freeBox___2Dx1B)}>
              <div className={classNames(projectcss.all, sty.freeBox___24Dpq)}>
                <div className={classNames(projectcss.all, sty.columns__vqh9E)}>
                  <div
                    className={classNames(projectcss.all, sty.column__jzYrX)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__w38Wr
                      )}
                    >
                      {
                        "With Coach, you’ll notice your knowledge improves right away - all while playing challenging games and having fun!"
                      }
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"section2"}
            data-plasmic-override={overrides.section2}
            className={classNames(projectcss.all, sty.section2)}
          >
            <div className={classNames(projectcss.all, sty.columns__nx6Uk)}>
              <div className={classNames(projectcss.all, sty.column__eDfK)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___4Jw6D)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__g0XA)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: webEmployees1PngTw3RXaUv7,
                      fullWidth: 761,
                      fullHeight: 561,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8Ow3Z
                    )}
                  >
                    {"Say ‘bye’ to boring trainings and onboardings"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zODoI
                    )}
                  >
                    {
                      "Coach allows you to go through any type of training in your spare time, at your own pace, coaching you until the most important parts of the training remain in your long-term memory."
                    }
                  </div>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__k3H6F)}>
                <div className={classNames(projectcss.all, sty.freeBox__rksZc)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__i0FB)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: webEmployees2Png3CSoMm4Uh,
                      fullWidth: 761,
                      fullHeight: 561,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xQ1QJ
                    )}
                  >
                    {"The games you can play at work"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oF1Ny
                    )}
                  >
                    {
                      "Coach gives you 8 different games to play and learn. Real games for adults. With different levels. Like Sudoku - it can get really challenging, right? "
                    }
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.columns__ocUfE)}>
              <div className={classNames(projectcss.all, sty.column___94YCe)}>
                <div className={classNames(projectcss.all, sty.freeBox__oYy6I)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__amAFk)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: webEmployees3Png1RI9KuqTz,
                      fullWidth: 761,
                      fullHeight: 561,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bcoud
                    )}
                  >
                    {"Stay aware of your knowledge and the gaps"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__riEhr
                    )}
                  >
                    {
                      "You don’t know what you don’t know, until a time comes to use that knowledge in practice. Coach helps you detect your knowledge gaps in a pile of various information - and pushes you to learn the parts that you don’t know - until you’ve mastered it all!"
                    }
                  </div>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__u5PWj)}>
                <div className={classNames(projectcss.all, sty.freeBox__kRmG)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___71Pau)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: webEmployees4PngTQlJi9Cl3,
                      fullWidth: 761,
                      fullHeight: 561,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uJhWh
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "See where your knowledge stands vs your colleagues "
                      : "See where your knowledge stands vs your colleagues "}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__il2AA
                    )}
                  >
                    {
                      "A little competition forces us to do better. Now you are able to see how your knowledge progressed over the time and where you stand between your colleagues. PS: if you are the best in the biz, Coach makes sure the management notices this."
                    }
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__okBjt)}>
            <div className={classNames(projectcss.all, sty.freeBox___4JzUp)}>
              <div className={classNames(projectcss.all, sty.columns__yjUEq)}>
                <div className={classNames(projectcss.all, sty.column__ilMnm)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gU6D
                    )}
                  >
                    {"READY TO START?"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__er8Ny
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Don’t just take our word.\nExperience the power of Coach yourself, and see the possibilities."
                      : "Don’t just take our word for it\nExperience the power of Coach\nyourself, and see the possibilities."}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__h4Nca)}
                  >
                    <button
                      className={classNames(
                        projectcss.all,
                        projectcss.button,
                        projectcss.__wab_text,
                        sty.button__yVRqa
                      )}
                    >
                      {"BOOK A DEMO"}
                    </button>

                    <button
                      className={classNames(
                        projectcss.all,
                        projectcss.button,
                        projectcss.__wab_text,
                        sty.button__xaOhz
                      )}
                    >
                      {"GET STARTED"}
                    </button>
                  </p.Stack>
                </div>

                <div className={classNames(projectcss.all, sty.column__ehYbb)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__jrUY)}
                    displayHeight={"100%"}
                    displayMaxHeight={"370px"}
                    displayMaxWidth={"220px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: phoneCutEmployeespngIt31Wkx6U,
                      fullWidth: 430,
                      fullHeight: 742,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </div>
          </div>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "menuHeaderDesktop", "hero", "h1", "section2", "footer"],
  menuHeaderDesktop: ["menuHeaderDesktop"],
  hero: ["hero", "h1"],
  h1: ["h1"],
  section2: ["section2"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicWhoIsItForEmployees__ArgProps,
          internalVariantPropNames: PlasmicWhoIsItForEmployees__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicWhoIsItForEmployees__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicWhoIsItForEmployees";
  } else {
    func.displayName = `PlasmicWhoIsItForEmployees.${nodeName}`;
  }
  return func;
}

export const PlasmicWhoIsItForEmployees = Object.assign(
  // Top-level PlasmicWhoIsItForEmployees renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    menuHeaderDesktop: makeNodeComponent("menuHeaderDesktop"),
    hero: makeNodeComponent("hero"),
    h1: makeNodeComponent("h1"),
    section2: makeNodeComponent("section2"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicWhoIsItForEmployees
    internalVariantProps: PlasmicWhoIsItForEmployees__VariantProps,
    internalArgProps: PlasmicWhoIsItForEmployees__ArgProps
  }
);

export default PlasmicWhoIsItForEmployees;
/* prettier-ignore-end */
